[package]
name = "Tester"
version = "0.1.0"
authors = ["Anatol <phonon19@rambler.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
